"""
Geodesic Submanifolds of H²_C for Harmonic Map Method

The Ernst equations describe harmonic maps from the base manifold M
to the complex hyperbolic 2-space H²_C. Solutions are generated by
restricting to totally geodesic submanifolds of H²_C.

Two types of geodesic submanifolds are implemented:

(a) Complex line:
    ξ = cos(2θ) * z
    η = sin(2θ) * z
    where z is a complex variable and θ controls GW/EM mixing.

(b) Lagrangian plane:
    Uses real coordinates (v₁, v₂) with
    v₁ + i*v₂ = 2z / (1 + |z|²)

Based on: Mishima & Tomizawa, Phys. Rev. D 110, 024038 (2024)
"""

import numpy as np
from abc import ABC, abstractmethod
from typing import Tuple, Optional, Callable
from .seeds import VacuumSeed


class GeodesicSubmanifold(ABC):
    """
    Abstract base class for geodesic submanifolds of H²_C.

    A geodesic submanifold provides a mapping from a vacuum seed solution
    ξ_v to an Einstein-Maxwell solution (ξ, η).
    """

    @abstractmethod
    def map_from_seed(self, xi_v: complex) -> Tuple[complex, complex]:
        """
        Map vacuum potential ξ_v to Einstein-Maxwell potentials (ξ, η).

        Args:
            xi_v: Vacuum reduced potential

        Returns:
            (ξ, η) tuple of complex potentials
        """
        pass

    @abstractmethod
    def inverse_map(self, xi: complex, eta: complex) -> complex:
        """
        Map (ξ, η) back to vacuum potential (if possible).

        Args:
            xi: Reduced gravitational potential
            eta: Reduced electromagnetic potential

        Returns:
            Vacuum potential ξ_v
        """
        pass

    def get_potentials(self, seed: VacuumSeed,
                       rho: float, t: float) -> Tuple[complex, complex]:
        """
        Get (ξ, η) at a spacetime point using the given seed.

        Args:
            seed: Vacuum seed solution
            rho, t: Spacetime coordinates

        Returns:
            (ξ, η) tuple
        """
        xi_v = seed.xi_v(rho, t)
        return self.map_from_seed(xi_v)


class ComplexLine(GeodesicSubmanifold):
    """
    Case (a): Complex line submanifold.

    The complex line in H²_C is parametrized by:
        ξ = cos(2θ) * z
        η = sin(2θ) * z

    where z is a complex variable (the vacuum potential ξ_v) and
    θ ∈ [0, π/4] is a mixing angle that controls the ratio of
    gravitational to electromagnetic content.

    Special cases:
    - θ = 0: Pure gravitational (η = 0)
    - θ = π/4: Equal mixing (|ξ| = |η|)

    For this submanifold, conversions near the axis revert to their
    initial state as the wave propagates to infinity.
    """

    def __init__(self, theta: float = np.pi / 8):
        """
        Initialize complex line submanifold.

        Args:
            theta: Mixing angle in [0, π/4]. Controls GW/EM ratio.
                   θ = 0 → pure gravitational
                   θ = π/4 → equal mixing
        """
        if not 0 <= theta <= np.pi / 4:
            raise ValueError(f"theta must be in [0, π/4], got {theta}")

        self.theta = theta
        self._cos_2theta = np.cos(2 * theta)
        self._sin_2theta = np.sin(2 * theta)

    def map_from_seed(self, xi_v: complex) -> Tuple[complex, complex]:
        """
        Map vacuum ξ_v to (ξ, η) on the complex line.

        ξ = cos(2θ) * ξ_v
        η = sin(2θ) * ξ_v
        """
        xi = self._cos_2theta * xi_v
        eta = self._sin_2theta * xi_v

        return (xi, eta)

    def inverse_map(self, xi: complex, eta: complex) -> complex:
        """
        Map (ξ, η) back to vacuum potential.

        For the complex line, ξ_v = ξ / cos(2θ) = η / sin(2θ)
        """
        if abs(self._cos_2theta) > abs(self._sin_2theta):
            return xi / self._cos_2theta
        else:
            return eta / self._sin_2theta

    def gravitational_fraction(self) -> float:
        """
        Theoretical gravitational mode fraction at this θ.

        Returns cos²(2θ) / (cos²(2θ) + sin²(2θ)) = cos²(2θ)
        """
        return self._cos_2theta**2

    def electromagnetic_fraction(self) -> float:
        """
        Theoretical electromagnetic mode fraction at this θ.

        Returns sin²(2θ)
        """
        return self._sin_2theta**2

    def __repr__(self) -> str:
        return f"ComplexLine(theta={self.theta:.4f})"


class LagrangianPlane(GeodesicSubmanifold):
    """
    Case (b): Totally real Lagrangian plane submanifold.

    The Lagrangian plane uses real coordinates (v₁, v₂) defined by:
        v₁ + i*v₂ = 2z / (1 + |z|²)

    This is a Cayley transform from the unit disc to the plane.

    For the solitonic seed (seed ii), this submanifold produces
    nontrivial mode conversions that persist to null infinity,
    with electromagnetic amplification factors from ~0.4 to ~2.4.

    The mapping to (ξ, η) is:
        z = ξ_v (vacuum potential interpreted as complex coordinate)
        v₁ = Re[2z / (1 + |z|²)]
        v₂ = Im[2z / (1 + |z|²)]

    Then back to (ξ, η):
        w = v₁ + i*v₂
        z_back = w / (1 - |w|²/4 + √[(1 - |w|²/4)² + 1])
        (simplified inverse Cayley)

    For the Lagrangian plane, the real and imaginary parts of z
    become the gravitational and electromagnetic components.
    """

    def __init__(self, em_scaling: float = 1.0):
        """
        Initialize Lagrangian plane submanifold.

        Args:
            em_scaling: Scaling factor for electromagnetic component.
                        Default 1.0 gives equal treatment.
        """
        self.em_scaling = em_scaling

    def map_from_seed(self, xi_v: complex) -> Tuple[complex, complex]:
        """
        Map vacuum ξ_v to (ξ, η) on the Lagrangian plane.

        The mapping uses:
        - Real part of ξ_v → gravitational component
        - Imaginary part of ξ_v → electromagnetic component (scaled)

        This gives a direct "splitting" of the complex vacuum potential.
        """
        # Cayley-like transformation
        # v₁ + i*v₂ = 2*z / (1 + |z|²)
        z = xi_v
        z_norm_sq = abs(z)**2

        if z_norm_sq > 100:
            # Large z: asymptotic behavior
            w = 2.0 / np.conj(z)
        else:
            w = 2 * z / (1 + z_norm_sq)

        v1 = w.real
        v2 = w.imag * self.em_scaling

        # Map (v1, v2) to (ξ, η)
        # Using a simple linear embedding into H²_C
        # ξ = v1 * (1 - v2²/4)
        # η = v2 * (1 - v1²/4)

        # Simplified version: treat as coordinates in Poincaré disc
        norm_sq = v1**2 + v2**2
        if norm_sq < 4:  # Inside the disc
            scale = 1.0 / (1 + norm_sq / 4)
            xi = v1 * scale + 0j
            eta = v2 * scale + 0j
        else:
            # Outside normal range, project back
            scale = 2.0 / np.sqrt(norm_sq)
            xi = v1 * scale * 0.5 + 0j
            eta = v2 * scale * 0.5 + 0j

        return (xi, eta)

    def inverse_map(self, xi: complex, eta: complex) -> complex:
        """
        Map (ξ, η) back to vacuum potential.

        Inverse of the Cayley-like transformation.
        """
        v1 = xi.real if isinstance(xi, complex) else xi
        v2 = (eta.real if isinstance(eta, complex) else eta) / self.em_scaling

        w = v1 + 1j * v2
        w_norm_sq = abs(w)**2

        if w_norm_sq < 1e-10:
            return 0.0 + 0.0j

        # Inverse Cayley: z = w / (1 - |w|²/4 + ...)
        # Simplified: z ≈ w * (1 + |w|²/4) for small |w|
        if w_norm_sq < 2:
            z = w * (1 + w_norm_sq / 4)
        else:
            # Large w
            z = 2.0 / np.conj(w)

        return z

    def __repr__(self) -> str:
        return f"LagrangianPlane(em_scaling={self.em_scaling})"


def create_composite_mapping(seed: VacuumSeed,
                             submanifold: GeodesicSubmanifold
                             ) -> Callable[[float, float], Tuple[complex, complex]]:
    """
    Create a composite mapping function (ρ, t) → (ξ, η).

    This combines a vacuum seed solution with a geodesic submanifold
    to produce an Einstein-Maxwell solution.

    Args:
        seed: Vacuum seed solution
        submanifold: Geodesic submanifold

    Returns:
        Function mapping (ρ, t) → (ξ, η)
    """
    def mapping(rho: float, t: float) -> Tuple[complex, complex]:
        xi_v = seed.xi_v(rho, t)
        return submanifold.map_from_seed(xi_v)

    return mapping
